layout_spectrum: 0.5053706
color:
  saturation: 0.9887217
  brandStrength: 0.8417029
  lightness: 0.9307196
  rhythmicContrast: 0.1412459
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.537594
name: CharlesGrid
